version: '3.8'

services:
  php:
    build: ./php
    volumes:
      - ./php/src:/var/www/html
    networks:
      - app-network

  nginx:
    image: nginx:1.24.0
    ports:
      - "80:80"
    volumes:
      - ./php/src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  mysql:
    image: mysql:5.7.34
    environment:
      MYSQL_ROOT_PASSWORD: exam888
      MYSQL_DATABASE: exam
      MYSQL_USER: exam
      MYSQL_PASSWORD: exam181818
    volumes:
      - ./mysql/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
